### ISSUE TITLE
Auto Leveling up doesn't seem to work

### ISSUE THREAD

**Issue by tiequan12345** [vfat-tools/adventure-party#10]
Hi there,

Been using the script well over the past few days, but now the auto leveling up function doesn't seem to actually level everyone up:

Barbarian (733309): level: 1, xp: 1000.0 (nb days to level up: 0). Next leveling 9/13/2021, 2:31:12 PM
Bard (733310): level: 1, xp: 1000.0 (nb days to level up: 0). Next leveling 9/13/2021, 2:31:12 PM
Cleric (733311): level: 1, xp: 1000.0 (nb days to level up: 0). Next leveling 9/13/2021, 2:31:12 PM
Druid (733312): level: 1, xp: 1000.0 (nb days to level up: 0). Next leveling 9/13/2021, 2:31:12 PM

I called the function manually in ftmscan and they're still level 1.  Any ideas?

**Comment by vfat0** [comment]
hey there was an error on one version of the contract where i used > instead of >=, can you check the code for this?

**Comment by tiequan12345** [comment]
Ah yeah, it looks like this contract was an older version.  Thanks
