### ISSUE TITLE
AdventureParty isn't deployed

### ISSUE THREAD

**Issue by emeraldhieu** [vfat-tools/adventure-party#12]
Hi, I've follow the instruction. Tests succeeded. Deployment worked.

hieunguyen@hieunguyen adventure-party % npx hardhat run scripts/deploy.ts
Creating Typechain artifacts in directory typechain for target ethers-v5
Successfully generated Typechain artifacts!
AdventureParty deployed to: 0x82e01223d51Eb87e16A03E24687EDF0F294da6f1
Summoming 1,2 adventurers, please wait...
Adventurer number 2's summoner ID is 2446751

When I search for that "0x82e01223d51Eb87e16A03E24687EDF0F294da6f1" in FTMScan, I didn't see any contract or transaction.

I tried deploying again. The same string "0x82e01223d51Eb87e16A03E24687EDF0F294da6f1" was returned.

What can I do to fix it?

**Comment by vfat0** [comment]
That is just a test of the deploy transaction, against hardhat's local network. To deploy on fantom you have to run:
`npx hardhat run scripts/deploy.ts --network fantom`
