### ISSUE TITLE
Is there a way to add already summoned adventurers to the contract party so I can adventure them all at one time?

### ISSUE THREAD

**Issue by Stcetjo** [vfat-tools/adventure-party#3]
Is there a way to add already summoned adventurers to the contract party so I can adventure them all at one time?

Thanks

**Comment by Stcetjo** [comment]
Figured it out! Thanks

**Comment by solsticesolutions** [comment]
How did you do it? just send the erc-721 tokens to the contract address?

**Comment by aboutlo** [comment]
hey @solsticesolutions you need to use `4` `sateTransfer` https://ftmscan.com/address/0xce761D788DF608BD21bdd59d6f4B54b2e27F25Bb#writeContract 

Then put  in `from`:  `0x_YOUR_ADDRESS`,  `to`: `0x_YOU_SMART_CONTRACT_ADDRESS`, `tokenId`: `THE_SUMMONER_ID`
