### ISSUE TITLE
Source Code Verification on FTMscan

### ISSUE THREAD

**Issue by solsticesolutions** [vfat-tools/adventure-party#4]
Hi,

Appreciate the update, I just ran and deployed the latest scripts.

The contract code isn't verified yet on ftmscan.com so I can't interact with the contract there. 

Was going through the verify process (not sure if I should as I didn't create it), but not sure where the ABI constructor arguments would be or if they are different than the old contract.

Thanks!

**Comment by vfat0** [comment]
just verified a new one now, did it work?

**Comment by vfat0** [comment]
i should add that its very easy to verify from the project's command line itself! `npx hardhat verify --network fantom your_contract_address_here`

**Comment by solsticesolutions** [comment]
That worked.

Thanks for the lesson too!
